name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur chaque push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Utilise l'environnement nommé 'production'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Google Cloud SDK
      id: cache-gcloud-sdk
      uses: actions/cache@v2
      with:
        path: /opt/hostedtoolcache/gcloud
        key: ${{ runner.os }}-gcloud
        restore-keys: |
          ${{ runner.os }}-gcloud-
    
    - name: Set up Cloud SDK
      if: steps.cache-gcloud-sdk.outputs.cache-hit != 'true'
      run: |
        curl -sSL https://sdk.cloud.google.com | bash
        echo "CLOUDSDK_PYTHON_SITEPACKAGES=1" >> $GITHUB_ENV
        echo "/opt/hostedtoolcache/gcloud/path.bash.inc" >> $GITHUB_ENV
    
    - name: Initialize Cloud SDK
      run: |
        gcloud --quiet components update
        gcloud --quiet config set project sacred-ember-377216
        gcloud --quiet auth activate-service-account 287953057890-compute@developer.gserviceaccount.com --key-file ${{ secrets.GCP_SA_KEY }}
    
    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet