name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Déclenche le déploiement sur chaque push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        project_id: sacred-ember-377216  # Remplacez par votre ID de projet Google Cloud
        service_account_key: ${{ secrets.GCP_SA_KEY }}  # Ajoutez votre clé de compte de service dans les secrets GitHub

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet