name: Test Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: GCP_SA_KEY

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Set environment variables
      run: echo "FIREBASE_SERVICE_ACCOUNT_KEY=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -c .)" >> $GITHUB_ENV
          
    - name: Run tests
      run: |
        pytest test_main.py