name: Test Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set FLASK_APP environment variable
      run: echo "FLASK_APP=app.py" >> $GITHUB_ENV

    - name: Run tests
      run: |
        flask db upgrade
        pytest